### ISSUE TITLE
Example data and scripts not unified

### ISSUE THREAD

**Issue by MedericFourmy** [agimus-project/happypose#132]
There are 2 ways to download the "crackers" example:
- Manually as explained in the docs: https://agimus-project.github.io/happypose/cosypose/inference.html#3-download-the-example
-> used for the `run_inference_on_example.py` script
- With the download script: `python -m happypose.toolbox.utils.download --examples crackers_example`
-> used for tests

Those two have confusingly slightly different structures.

Should we remove one of them?
Or both and keep only the barbecue-sauce example?

**Comment by nim65s** [comment]
The structure of those examples (if we have multiple ones) should be unified.
I think using the script to download the data is better than providing manual instructions

**Comment by MedericFourmy** [comment]
I agree with both, it's even simpler to keep only the barbecue-sauce example that has a more complete set of data (bounding box detection, depth).
