### ISSUE TITLE
bop_toolkit_lib is in fact not an optional dependency

### ISSUE THREAD

**Issue by MedericFourmy** [agimus-project/happypose#153]
It is imported in modules that are not related to pure evaluation, such as [web dataset](https://github.com/agimus-project/happypose/blob/deb096554ab3e0beae62be9d625b4ea2e12be10d/happypose/toolbox/datasets/web_scene_dataset.py#L30) which is imported in the standard bop dataset loading utility [here](https://github.com/agimus-project/happypose/blob/deb096554ab3e0beae62be9d625b4ea2e12be10d/happypose/toolbox/datasets/datasets_cfg.py#L46).

We currently rely on our own fork due to the fact the original setup scripts require to modify some [modules directly](https://github.com/thodan/bop_toolkit/blob/8facae674f752f9680c4d2a75bc951a6fd947f1e/bop_toolkit_lib/config.py#L18). 

This might conflict with our current packaging effort.

**Comment by nim65s** [comment]
fixed somewhere, broken in #160, fixed again in #160
