### ISSUE TITLE
Paris data not available

### ISSUE THREAD

**Issue by nim65s** [agimus-project/happypose#174]
https://www.paris.inria.fr is currently down

**Comment by nim65s** [comment]
https://www.paris.inria.fr/ now up, but https://www.paris.inria.fr/archive_ylabbeprojectsdata/ forbidden. This was reported.

**Comment by MedericFourmy** [comment]
@nim65s It seems like we can close this issue?

**Comment by nim65s** [comment]
yep, thanks !
