### ISSUE TITLE
Proper bop_toolkit_lib installation

### ISSUE THREAD

**Issue by MedericFourmy** [agimus-project/happypose#35]
In current `dev` branch, [this line of web_scene_dataset,py](https://github.com/agimus-project/happypose/blob/a050003ea04afbb9108e8d4636af884696690731/happypose/toolbox/datasets/web_scene_dataset.py#L33), the bop_toolkit_lib.dataset is requested. However, it seems that the `bop_toolkit_challenge` in `deps` folder does not implement the `dataset` submodule.
Are we missing the latest version of the `bop_toolkit_challenge` package?

**Comment by ylabbe** [comment]
It's in this PR https://github.com/thodan/bop_toolkit/pull/87 that hasn't been merged. I am not sure what is the good solution:
- 1. Install bop toolkit from this branch
- 2. Update `bop_toolkit` in `deps`
- 3. Copy useful parts of the code to the repository [probably not a good idea]
- 4. something else ?
Any ideas how to deal with such situation @nim65s ?

**Comment by nim65s** [comment]
@MedericFourmy could you try first to install bop toolkit from the PR branch ?

**Comment by MedericFourmy** [comment]
Sure it works, I just had to remove versions from bop_toolkit requirements.txt before, there were some dependency conflicts.

**Comment by MedericFourmy** [comment]
https://github.com/thodan/bop_toolkit/pull/87 was merged, this is not a problem anymore
