### ISSUE TITLE
Megapose detector: error when no detections

### ISSUE THREAD

**Issue by MedericFourmy** [agimus-project/happypose#94]
Megapose pose_estimator main entry point `run_inference_pipeline` covers different behviours depending on the 

https://github.com/agimus-project/happypose/blob/6a9b1726bebf69f76c3743758450e4118fafeb0d/happypose/pose_estimators/megapose/inference/pose_estimator.py#L520

- if coarse_estimates is not None: only refine initial coarse poses and detections   
else
- if detections is None and run_detector True                -> run the detection model
- if detections is not None and run_detector == True   -> use the detections 
- if detections is None and run_detector == False         -> assertion error

One case is not handled though: 
- len(detections) == 0 
which can happen if the model does not detect any object or the detections passed to  run_inference_pipeline are empty

which causes an error in 

https://github.com/agimus-project/happypose/blob/6a9b1726bebf69f76c3743758450e4118fafeb0d/happypose/pose_estimators/megapose/inference/pose_estimator.py#L577

```
ValueError: 'batch_im_id' is both an index level and a column label, which is ambiguous.
```

**Comment by nim65s** [comment]
done in #92 & #102
