### ISSUE TITLE
download.py --bop_dataset fails on next-pack branch

### ISSUE THREAD

**Issue by MedericFourmy** [agimus-project/happypose#96]
`python -m happypose.toolbox.utils.download --bop_dataset ycbv`

Only manages to download

```
https://bop.felk.cvut.cz/media/data/bop_datasets/ycbv_base.zip
https://bop.felk.cvut.cz/media/data/bop_datasets/ycbv_models.zip
```

and fails silently on other files, in particular

`https://bop.felk.cvut.cz/media/data/bop_datasets/ycbv_train_synt.zip`

I guess that:

https://github.com/agimus-project/happypose/blob/f61a0b0422ad6d196d2eb567b148137591f788e7/happypose/toolbox/utils/download.py#L394

raises an exception that is not `httpx.PoolTimeout` but I did not manage to catch it.

The only error message at the end of the script is `Killed`.

**Comment by nim65s** [comment]
Thanks for the report. It looks like everything is downloaded in RAM first, and then written to disk after. 
So when you try to download filres that are bigger than your ram, it fails.
I'll fix it.

**Comment by nim65s** [comment]
@MedericFourmy : this should be fixed. Can you try again and close the PR if this is OK ?

**Comment by MedericFourmy** [comment]
Yes it works now, I close the issue
